# Generated by Django 5.2.11 on 2026-02-21 06:30

import checklists.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('suggested_for', models.CharField(blank=True, help_text="Advisory tag, e.g. 'Kitchen', 'Bar', 'Floor'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Library Template',
                'verbose_name_plural': 'Library Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, help_text='Auto-generated from frequency and time settings', max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('bi_weekly', 'Bi-Weekly')], max_length=10)),
                ('time_of_day', models.TimeField(default='08:00', help_text='Default is 8:00 AM if not specified')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Required for Weekly and Bi-Weekly schedules', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Required for Monthly schedules (1-28)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('requires_supervisor', models.BooleanField(default=False, help_text='If checked, this checklist requires supervisor validation before being marked complete.')),
                ('validity_window_hours', models.IntegerField(default=3, help_text='Hours after scheduled time that checklist can be completed (default 3). After this window, checklist expires.')),
                ('supervisor_validity_window_hours', models.IntegerField(default=2, help_text='Hours after staff completion that supervisor has to verify & sign off (default 2). After this window, verification expires.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_label', models.CharField(db_index=True, max_length=50)),
                ('created_by', models.CharField(max_length=6)),
                ('completed_by', models.CharField(blank=True, help_text='Name of person who completed this checklist', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed'), ('verified', 'Double-Verified'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted')], db_index=True, default='pending', max_length=15)),
                ('validity_window_hours', models.IntegerField(blank=True, help_text='Snapshotted from template at creation time.', null=True)),
                ('supervisor_validity_window_hours', models.IntegerField(blank=True, help_text='Snapshotted from template at creation time.', null=True)),
                ('scheduled_time', models.TimeField(blank=True, help_text='Snapshotted from template schedule at creation time. Null for manually-created instances.', null=True)),
                ('supervisor_signed_off', models.BooleanField(default=False)),
                ('supervisor_signature', models.TextField(blank=True, help_text='Base64 encoded PNG supervisor signature')),
                ('supervisor_name', models.CharField(blank=True, max_length=100)),
                ('supervisor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.checklisttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstanceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_item_id', models.UUIDField()),
                ('item_text', models.CharField(max_length=500)),
                ('response_type', models.CharField(default='yes_no', max_length=10)),
                ('response_value', models.CharField(blank=True, max_length=500)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=checklists.models.photo_upload_path)),
                ('photo_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_confirmed', models.BooleanField(blank=True, null=True)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklistinstance')),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=checklists.models.flag_photo_upload_path)),
                ('photo_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('acknowledgement_signature', models.TextField(blank=True)),
                ('instance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='checklists.instanceitem')),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=48)),
                ('task_type', models.CharField(choices=[('yes_no', 'Yes / No'), ('number', 'Number'), ('text', 'Text'), ('photo', 'Photo')], default='yes_no', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('library_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='checklists.librarytemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_data', models.TextField(help_text='Base64 encoded PNG signature image')),
                ('signed_by', models.CharField(blank=True, max_length=100)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='checklists.checklistinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('staff_pin', models.CharField(blank=True, default='', max_length=4)),
                ('supervisor_pin', models.CharField(blank=True, default='', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='checklists.outlet')),
            ],
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.team'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='supervisor_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_checklists', to='checklists.team'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instances', to='checklists.team'),
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=48)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('response_type', models.CharField(choices=[('yes_no', 'Yes / No'), ('number', 'Number'), ('text', 'Text'), ('photo', 'Photo')], default='yes_no', max_length=10)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GroupOutletScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_scopes', to='auth.group')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_scopes', to='checklists.outlet')),
            ],
            options={
                'unique_together': {('group', 'outlet')},
            },
        ),
    ]
