# Generated by Django 6.0.2 on 2026-02-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='team',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='template',
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.schedule'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='team',
            field=models.ForeignKey(default='b18c765d-6b6c-453e-a1ea-5211317291fd', on_delete=django.db.models.deletion.CASCADE, to='checklists.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='Default Schedule', max_length=100),
            preserve_default=False,
        ),
    ]
