# Generated by Django 5.2.11 on 2026-02-22 02:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_librarytemplate_librarytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceitem',
            name='auto_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instanceitem',
            name='temp_threshold_lower',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='instanceitem',
            name='temp_threshold_upper',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='auto_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='temp_threshold_lower',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='temp_threshold_upper',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='groupoutletscope',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instanceitem',
            name='response_type',
            field=models.CharField(default='yes_no', max_length=15),
        ),
        migrations.AlterField(
            model_name='librarytask',
            name='task_type',
            field=models.CharField(choices=[('yes_no', 'Yes / No'), ('number', 'Number'), ('text', 'Text'), ('photo', 'Photo'), ('temperature', 'Temperature')], default='yes_no', max_length=15),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='response_type',
            field=models.CharField(choices=[('yes_no', 'Yes / No'), ('number', 'Number'), ('text', 'Text'), ('photo', 'Photo'), ('temperature', 'Temperature')], default='yes_no', max_length=15),
        ),
    ]
