# Generated by Django 6.0.2 on 2026-02-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_remove_schedule_team_remove_schedule_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceitem',
            name='response_type',
            field=models.CharField(default='checkbox', max_length=10),
        ),
        migrations.AddField(
            model_name='instanceitem',
            name='response_value',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='response_type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('number', 'Number'), ('text', 'Text')], default='checkbox', max_length=10),
        ),
    ]
