# Generated by Django 6.0.2 on 2026-02-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_instanceitem_response_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='completed_by',
            field=models.CharField(blank=True, help_text='Name of person who completed this checklist', max_length=100),
        ),
    ]
