# Generated by Django 6.0.2 on 2026-02-18 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_checklistinstance_completed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_data', models.TextField(help_text='Base64 encoded PNG signature image')),
                ('signed_by', models.CharField(blank=True, max_length=100)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='checklists.checklistinstance')),
            ],
        ),
    ]
