# Generated by Django 5.2.11 on 2026-02-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_auto_flag_rules_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('outlet', 'name')},
        ),
    ]
