# Generated by Django 5.2.11 on 2026-02-24 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_alter_outlet_name_alter_team_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='default_supervisor_team',
            field=models.ForeignKey(blank=True, help_text='Default supervisor team for this checklist. Any outlet supervisor can still verify.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_templates', to='checklists.team'),
        ),
    ]
