# Generated by Django 6.0.2 on 2026-02-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_alter_response_type_yes_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateitem',
            name='text',
            field=models.CharField(max_length=48),
        ),
    ]
