# Generated by Django 6.0.2 on 2026-02-19 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_template_item_48_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='supervisor_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded PNG supervisor signature'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='supervisor_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='supervisor_signed_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='supervisor_team',
            field=models.ForeignKey(blank=True, limit_choices_to={'team_type': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_checklists', to='checklists.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('supervisor', 'Supervisor')], default='staff', max_length=10),
        ),
        migrations.AlterField(
            model_name='checklistinstance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed'), ('verified', 'Double-Verified')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='checklistinstance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instances', to='checklists.team'),
        ),
    ]
