# Generated by Django 6.0.2 on 2026-02-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_checklistinstance_supervisor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='requires_supervisor',
            field=models.BooleanField(default=False, help_text='If checked, this checklist requires supervisor validation before being marked complete.'),
        ),
    ]
