# Generated by Django 6.0.2 on 2026-02-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_checklisttemplate_requires_supervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'schedules'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_month',
            field=models.IntegerField(blank=True, help_text='Required for Monthly schedules (1-28)', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Required for Weekly and Bi-Weekly schedules', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('bi_weekly', 'Bi-Weekly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_of_day',
            field=models.TimeField(default='08:00', help_text='Default is 8:00 AM if not specified'),
        ),
    ]
