# Generated by Django 6.0.2 on 2026-02-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0011_alter_schedule_options_schedule_day_of_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='validity_window_hours',
            field=models.IntegerField(default=3, help_text='Hours after scheduled time that checklist can be completed (default 3). After this window, checklist expires.'),
        ),
        migrations.AlterField(
            model_name='checklistinstance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed'), ('verified', 'Double-Verified'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
