# Generated by Django 6.0.2 on 2026-02-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0012_checklisttemplate_validity_window_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='supervisor_validity_window_hours',
            field=models.IntegerField(default=2, help_text='Hours after staff completion that supervisor has to verify & sign off (default 2). After this window, verification expires.'),
        ),
    ]
