# Generated by Django 6.0.2 on 2026-02-19 12:21

import checklists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0013_checklisttemplate_supervisor_validity_window_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=checklists.models.photo_upload_path),
        ),
        migrations.AddField(
            model_name='instanceitem',
            name='photo_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='response_type',
            field=models.CharField(choices=[('yes_no', 'Yes / No'), ('number', 'Number'), ('text', 'Text'), ('photo', 'Photo')], default='yes_no', max_length=10),
        ),
    ]
