# Generated by Django 5.2.11 on 2026-02-20 08:53

import checklists.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0014_instanceitem_photo_instanceitem_photo_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(editable=False, help_text='Auto-generated from frequency and time settings', max_length=100),
        ),
        migrations.CreateModel(
            name='FlaggedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=checklists.models.flag_photo_upload_path)),
                ('photo_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('instance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='checklists.instanceitem')),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
    ]
