# Generated by Django 5.2.11 on 2026-02-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0017_supervisor_review_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='supervisor_validity_window_hours',
            field=models.IntegerField(blank=True, help_text='Snapshotted from template at creation time.', null=True),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='validity_window_hours',
            field=models.IntegerField(blank=True, help_text='Snapshotted from template at creation time.', null=True),
        ),
    ]
