# Generated by Django 5.2.11 on 2026-02-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0018_checklistinstance_supervisor_validity_window_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Snapshotted from template schedule at creation time. Null for manually-created instances.', null=True),
        ),
    ]
