# Generated by Django 5.2.11 on 2026-02-21 00:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('checklists', '0019_checklistinstance_scheduled_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOutletScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_scopes', to='auth.group')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_scopes', to='checklists.outlet')),
            ],
            options={
                'unique_together': {('group', 'outlet')},
            },
        ),
    ]
