# Generated by Django 5.2.11 on 2026-02-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0020_groupoutletscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='passcode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('outlet', 'passcode')},
        ),
    ]
