# Generated by Django 5.2.11 on 2026-02-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0021_alter_team_passcode_alter_team_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='passcode',
            field=models.CharField(max_length=4),
        ),
    ]
