# Generated by Django 5.2.11 on 2026-02-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0022_alter_team_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinstance',
            name='date_label',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='checklistinstance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed'), ('verified', 'Double-Verified'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='flaggeditem',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='flaggeditem',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['outlet', 'team_type'], name='checklists__outlet__2a3cc5_idx'),
        ),
    ]
