# Generated by Django 5.2.11 on 2026-02-21 03:06

import django.db.models.deletion
from django.db import migrations, models


def copy_passcode_to_pins(apps, schema_editor):
    """Copy existing passcode values to the appropriate PIN field based on team_type."""
    Team = apps.get_model('checklists', 'Team')
    for team in Team.objects.all():
        if team.team_type == 'staff':
            team.staff_pin = team.passcode
        elif team.team_type == 'supervisor':
            team.supervisor_pin = team.passcode
        team.save(update_fields=['staff_pin', 'supervisor_pin'])


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0023_alter_checklistinstance_date_label_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='team',
            name='checklists__outlet__2a3cc5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='team',
            name='staff_pin',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='team',
            name='supervisor_pin',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        # Copy data before removing old fields
        migrations.RunPython(copy_passcode_to_pins, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='checklistinstance',
            name='supervisor_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_checklists', to='checklists.team'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='passcode',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_type',
        ),
    ]
